name: goes-16
channels:
- conda-forge
- defaults
dependencies:
- backports
- backports.functools_lru_cache
- basemap=1.1.0
- basemap-data-hires
- boost
- boost-cpp
- bzip2
- ca-certificates
- cairo
- certifi
- curl
- cycler
- dbus
- expat
- fontconfig
- freetype
- freexl
- geos
- geotiff
- gettext
- giflib
- glib
- gst-plugins-base
- gstreamer
- hdf4
- hdf5
- icu
- jpeg
- json-c
- kealib
- krb5
- libdap4
- libffi
- libgdal
- libiconv
- libkml
- libnetcdf
- libpng
- libpq
- libspatialite
- libssh2
- libtiff
- libxcb
- libxml2
- matplotlib
- ncurses
- openjpeg
- openssl
- pcre
- pip
- pixman
- poppler
- poppler-data
- proj4
- pyparsing
- pyproj
- pyqt
- pyshp
- python=3.*
- python-dateutil
- pytz
- qt
- readline
- setuptools
- sip
- six
- sqlite
- tk
- tornado
- wheel
- xerces-c
- xorg-libxau
- xorg-libxdmcp
- xz
- zlib
- gdal
- intel-openmp
- libgcc-ng
- libgfortran
- libgfortran-ng
- mkl
- netcdf4
- numpy
- util-linux
- pip:
  - backports.functools-lru-cache==1.4
